spring:
  application:
    name: workplace_reservation

  datasource:
    username: admin
    password: root
    url: jdbc:postgresql://localhost:5433/workplace-reservation-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
