spring:
  application:
    name: workplace_reservation
  liquibase:
    enabled: true
  datasource:
    username: admin
    password: root
    url: jdbc:postgresql://localhost:5433/workplace-reservation-db
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        default_schema: workplace_reservation

jwt:
  lifetime: 1d
  secret: workplace_secret